# Generated by Django 4.1.4 on 2022-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Payment_Date',
            field=models.DateField(default=None),
        ),
    ]
