# Generated by Django 4.1.4 on 2022-12-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_user_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Payment_Date',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 10, 49, 10, 225417, tzinfo=datetime.timezone.utc)),
        ),
    ]
