# Generated by Django 4.1.4 on 2022-12-13 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_user_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Payment_Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 18, 46, 32, 33512, tzinfo=datetime.timezone.utc)),
        ),
    ]
